# Generated by Django 5.2.10 on 2026-02-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
