# Generated by Django 5.2.10 on 2026-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
