# Generated by Django 5.2.10 on 2026-02-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
